language: java

sudo: false

addons:
  hosts:
    - db

services:
  - docker

install:
  - docker build db/. --default-authentication-plugin=mysql_native_password
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - mvn clean

jobs:
  include:
    - stage: unit tests
      install: skip
      jdk: oraclejdk11
      script: mvn test -Dtest=com.napier.sem.AppTest -DfailIfNoTests=false
    - stage: integration tests
      jdk: oraclejdk11
      script: mvn test -Dtest=com.napier.sem.AppIntegrationTest
    - stage: deploy
      install: skip
      jdk: oraclejdk11
      script: echo "Deploy"

stages:
  - unit tests
  - integration tests
  - name: deploy
    if: branch = master

after_success:
  - docker-compose up --abort-on-container-exit