version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  # db is is db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always